### PR TITLE
Fix arclength

### PR DESCRIPTION
**Pull request by drewyoungren**
Did a few things, in increasing order of significance:
- Fixed the math exposition.
- Added an example curve
  - `exampleCurves` is now an object and adding to in will automatically populate the dropdown menu (via Svelte `#each` loop).  
- Added a slider for interactive discretization of curve. 
  - User sets the number of Vectors to chop the curve into.
  - This just appends vectors to the global `objects` array, but I added a `show` parameter to Vector.svelte that prevents its display in the Objects list.

### CODE REVIEW

**Comment by drewyoungren** [comment]
Not sure why eslint failed for the stray character. I fixed in in subsequent commit.

**Comment by nikolas** [comment]
No worries, we can do the work of adapting this to our 4-space indentation standards. We may open a new pull request for this functionality while referencing this branch, if we can't get this passing. Anyways thanks! Looks like some valuable new stuff here.

**Comment by drewyoungren** [comment]
I have VSCode set to 4 spaces. The issues (1 left I think) are more about the LaTeX typesetting and svelte and MathJax playing nice together with their `{}`'s. @Evan-CTL likely has a better handle on these.

**Comment by drewyoungren** [comment]
Hmmm, obviously I am having trouble counting spaces. Not sure why it's using 2-spaces on save. 

Anyone know where I might have set other autoformatters?

image

**Comment by Evan-CTL** [comment]
> Hmmm, obviously I am having trouble counting spaces. Not sure why it's using 2-spaces on save.
> 
> Anyone know where I might have set other autoformatters?
> 
> image

I imagine there is a configuration option that you could modify, you'd have to look into what formatter you're using. Otherwise it's okay to disable the autoformatter.

**Comment by drewyoungren** [comment]
I got the checks to pass. At least with the `fix-chapters` branch. I don't know if `main` has moved on.

**Comment by Evan-CTL** [comment]
I saw it. It appeared to run smoothly otherwise when I ran it locally. I think this is exclusively the linter complaining about some non-standard practices, but we I think that we can preserve your style of entry for the equations if we disable the linter checks in between the <M> tags, if you prefer. 

I was looking into it, but I'll have to pick it back up tomorrow. Sent you an email that says much of the same.

**Comment by nikolas** [comment]
@Evan-CTL this branch was merged into the fix-chapters branch rather than main - was that intentional? We generally always merge pull requests to the main branch (whether it's called main or master).

**Comment by Evan-CTL** [comment]
@nikolas  Yes, it's okay. It was mergable to my branch but not to main. I was going to rebase it so that it will be ready for the merge into production.

**Comment by nikolas** [comment]
Ah okay, makes sense.

**Comment by nikolas** [comment]
You might have trouble rebasing all these changes alongside your changes.. the way I would do it is just make a new branch - smaller and more focused changes on separate branches are easier to work with. You can do whatever works though.

**Comment by Evan-CTL** [comment]
Already rebased. Just going through it to make sure everything changed
smoothly. Getting some gacontext errors.

**Pull request merged**
