### PR TITLE
Lay out poll submission flow

### PR DESCRIPTION
**Pull request by nikolas**
* Introduce d3.js for response aggregate

### CODE REVIEW

**Comment by Evan-CTL** [comment]
Is this anything to worry about?
Screen Shot 2022-12-13 at 1 08 44 PM

**Comment by nikolas** [comment]
This is an issue with how d3 is organized, but it shouldn't actually cause any problems: https://stackoverflow.com/a/69078310/173630

**Comment by Evan-CTL** [comment]
> This is an issue with how d3 is organized, but it shouldn't actually cause any problems: https://stackoverflow.com/a/69078310/173630

Should we suppress the warning then?

**Comment by Evan-CTL** [comment]
I've noticed a few bugs in the Poll implementation.
1. Hitting Cancel as the presenter will lock you out of the polls window. You have to leave the room to get out
2. Viewers can only receive one poll question. Whether they answer it or not it doesn't go away or get overwritten by new prompts.
3. If a viewer enters the room after a poll has been sent the presenter can send them a new poll, however whatever they answer is received as a response to the current poll. This means that you can mix responses from the multiple choice and numeric value questions. Elements of this are useful as the instructor could resend a poll if someone missed the prompt or lost connection, but it does allow the mixing of poll responses. Maybe a `poll id` or a `resend poll` button could help.
4. There is a visual overlap of the Responses title and the response graphs.

If these are known issues to be handled in a later task then I will merge the branch. I can write them up as issues if you like.

**Comment by nikolas** [comment]
The warning is valid but it's just a warning, I think we can leave it. d3 just tends to do things its own way. Apparently this issue actually crashed older versions of rollup, but the current version of rollup can handle it. The actual circular dependency shouldn't cause any issues because they have some lazy loading thing set up. As long as the code compiles with rollup, it is fine.

Thank you for the QA - I will address these issues on this branch. This is a very rough implementation so far and I might as well get it in better shape here.

And yeah - I'm definitely aware of the student entering room after poll is sent issue: I'll have to hook up the currentPoll state up to the redis back-end similarly to how we have scene state working.

**Comment by nikolas** [comment]
This branch can be reviewed again - I still have more to implement, like the persistent polls feature. Some live polling is basically working though.

**Comment by Evan-CTL** [comment]
Looking better!
Keep in mind it doesn't look like the response stacks: 
- For Multiple choice questions it'll make a different bar for like-responses
- For the numeric response it records the multiple responses, but either the new number with the same response replaces the old one or it doesn't add to the value. 
  - Given a test with 3 respondents the response with 2 like-responses was the same value and size as the response with 1 like-response.

Will merge right now, but I wanted to make a note of this.

**Pull request merged**
